# gems
whitelist:
  - jekyll-redirect-from
  - jekyll-github-metadata

plugins:
  - jekyll-redirect-from
  - jekyll-github-metadata

# files
exclude:
  - Makefile
  - README.md
  - Gemfile
  - Gemfile.lock
  - CNAME
  - vendor
  - _deprecated

# Markdown
highlighter: false
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true
  syntax_highlighter_opts:
    disable: true

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: "default"
      type: article
      category: "Others"

# Site info
url: http://ricostacruz.com/cheatsheets
title: Cheatsheets

# Google analytics
analytics:
  hostname: ricostacruz.com
  id: "UA-20473929-1"

category_names:
  - Ansible
  - Apps
  - CLI
  - CSS
  - Devops
  - Elixir
  - Git
  - HTML
  - JavaScript
  - JavaScript libraries
  - Jekyll
  - Ledger
  - Markup
  - Node.js
  - Rails
  - React
  - Ruby
  - Ruby libraries
  - Vim
  - Others

# https://help.github.com/articles/repository-metadata-on-github-pages/
repository: rstacruz/cheatsheets
