# Jekyll configuration

whitelist:
  - jekyll-redirect-from
  - jekyll-github-metadata

plugins:
  - jekyll-redirect-from
  - jekyll-github-metadata

exclude:
  - Makefile
  - README.md
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - CNAME
  - vendor

# Markdown

highlighter: false
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true
  syntax_highlighter_opts:
    disable: true

# Defaults

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: "default"
      type: article
      category: "Others"
      excerpt_separator: "<!--more-->"
      prism_languages:
        - jsx
        - bash
        - scss
        - css
        - elixir
        - ruby

# Site info

url: http://ricostacruz.com/cheatsheets
title: Cheatsheets

# GitHub metadata
# https://help.github.com/articles/repository-metadata-on-github-pages/

repository: rstacruz/cheatsheets
