# files
layouts: ./_/layouts
destination: ./_/site
sass:
  sass_dir: ./_/sass

# Markdown
highlighter: pygments
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true
  use_coderay: true

  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Site info
url: http://ricostacruz.com/cheatsheets
meta:
  name: "Cheatsheets"
  title: Cheatsheets
  description: "A collection of cheatsheets I've written."
  hostname: ricostacruz.com
  author: Rico Sta. Cruz

# Google analytics
analytics:
  id: "UA-20473929-1"
