# files
layouts: ./_/layouts
destination: ./_/site
sass:
  sass_dir: ./_/sass

# Markdown
highlighter: pygments
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  parse_block_html: true

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

# Site info
url: http://ricostacruz.com/cheatsheets
title: Cheatsheets

# Google analytics
analytics:
  hostname: ricostacruz.com
  id: "UA-20473929-1"
